# Generated by Django 5.1 on 2024-10-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_type', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
