# Generated by Django 5.1 on 2024-10-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
