# Generated by Django 5.1 on 2024-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_books_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
