# Generated by Django 5.1 on 2024-10-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
    ]
