# Generated by Django 5.1 on 2024-10-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('book_type', models.CharField(max_length=200)),
                ('book_image', models.ImageField(default='', upload_to='store')),
                ('quantity', models.IntegerField(default=1, max_length=700)),
                ('total_price', models.IntegerField(default=0, max_length=700)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.books')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
