# Generated by Django 5.1 on 2024-10-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book_name',
        ),
    ]
